---
  deployment:
      tasks:
          - export DEPLOYPATH=/home/ajwebdev/public_html/
          - /bin/cp index.html $DEPLOYPATH
          - /bin/cp projects.html $DEPLOYPATH
          - /bin/cp style.css $DEPLOYPATH
          - /bin/cp -R images $DEPLOYPATH
          - /bin/cp -R video $DEPLOYPATH
          - /bin/cp tipcalculator.html $DEPLOYPATH
